library(shiny)
library(reticulate)

# may need to restart R in between switches:
# use_virtualenv("venvnew/bin/activate") # may need this
# may need to turn Tools --> global options --> python to miniconda most recently updated
RETICULATE_PYTHON="venvnew/bin/python" # Attention: try running first without this
# py_install("numpy") # this works to install anything missing from venv

# The below works to run python script
   # as long as venv up and working
# py_run_file(paste0(getwd(),"/appCeltics/apiCalls.py"))
# for actual app run, may need to drop additional appCeltics/
py_run_file(paste0(getwd(),"/apiCalls.py"))


# server-side code block, which defines three arguments
function(input, output, session) {
  
  RETICULATE_PYTHON="venvnew/bin/python"
  # The below works to run python script
  # as long as venv up and working
  # py_run_file(paste0(getwd(),"/appCeltics/apiCalls.py"))
  # for actual app run, may need to drop additional appCeltics/
  py_run_file(paste0(getwd(),"/apiCalls.py"))
  r_df <- py$df # assigning python variables as R variables
  
    # Instantiate new output called 'distPlot' generated by code block within renderPlot()
    output$distPlot <- renderPlot({

        # generate bins based on input$bins from ui.R
        x    <- r_df[,"AST_TOV"] # extracts second column of 'faithful' dataset
        # input$bins utilizes bin variable to set length.out
        bins <- seq(min(x), max(x), length.out = input$bins + 1) 

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkblue', border = 'black',
             xlab = 'AST_TOV',
             main = 'Histogram of AST_TOV')
    })
}
