library(shiny)
library(reticulate)

# may need to restart R in between switches:
# use_virtualenv("venvnew/bin/activate") # may need this
# may need to turn Tools --> global options --> python to miniconda most recently updated
RETICULATE_PYTHON="venvnew/bin/python" # Attention: try running first without this
# py_install("numpy") # this works to install anything missing from venv

# The below works to run python script
   # as long as venv up and working
# py_run_file(paste0(getwd(),"/appCeltics/apiCalls.py"))
# for actual app run, may need to drop additional appCeltics/
py_run_file(paste0(getwd(),"/apiCalls.py"))

# Not needed, but this is how we read in other R scripts from current directory
# source("data.R") 

# server-side code block, which defines three arguments
shinyServer(function(input, output, session) {
  
  RETICULATE_PYTHON="venvnew/bin/python"
  # The below works to run python script
  # as long as venv up and working
  # py_run_file(paste0(getwd(),"/appCeltics/apiCalls.py"))
  # for actual app run, may need to drop additional appCeltics/
  py_run_file(paste0(getwd(),"/apiCalls.py"))
  r_df <- py$df # assigning python variables as R variables
  
    # Instantiate new output called 'distPlot' generated by code block within renderPlot()
    output$distPlot <- renderPlot({

        # generate bins based on input$bins from ui.R
        x    <- r_df[,"AST_TOV"] # extracts second column of 'faithful' dataset
        # input$bins utilizes bin variable to set length.out
        bins <- seq(min(x), max(x), length.out = input$bins + 1) 

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkblue', border = 'black',
             xlab = 'AST_TOV',
             main = 'Histogram of AST_TOV')
    })
    
    # Create scatter plot 1
    output$scatterPlot1 <- renderPlot({
      plot(r_df$MIN, r_df$PTS, 
           xlab = "Minutes Played", ylab = "Points",
           main = "Scatter Plot 1")
    })
    
    # Create scatter plot 2
    output$scatterPlot2 <- renderPlot({
      filtered_data <- subset(r_df, TEAM == input$team_selector)
      plot(filtered_data$MIN, filtered_data$PTS, 
           xlab = "Minutes Played", ylab = "Points",
           main = "Scatter Plot 2")
    })
    
    # Create scatter plot 3
    output$scatterPlot3 <- renderPlot({
      filtered_data <- subset(r_df, PTS > input$pts_threshold)
      plot(filtered_data$MIN, filtered_data$PTS, 
           xlab = "Minutes Played", ylab = "Points",
           main = "Scatter Plot 3")
    })
    
    
})
